version: '3.9'

services:
  testing_sec_pass:
    build: .
    container_name: testing_sec_pass_app
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    # We run Gunicorn here
    command: gunicorn --workers 2 --threads 4 --timeout 120 --bind 0.0.0.0:8000 app:app
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: testing_sec_pass_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - testing_sec_pass
    restart: always
