version: '3.9'

services:
  testing_sec_pass:
    build: .
    container_name: testing_sec_pass_app
    volumes:
      - ./:/app
    env_file:
      - .env
    # We run Gunicorn here
    command: gunicorn --timeout 300 --bind 0.0.0.0:8000 app:app
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    container_name: testing_sec_pass_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - testing_sec_pass
