version: '3.9'

services:
  testing_sec_pass:
    image: testing_sec_pass
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testing_sec_pass
    volumes:
      - ./:/app  # Mounts current directory into /app inside the container
    env_file:
      - .env     # <-- This loads all variables from .env into the container
    working_dir: /app
    command: python sec_pass/tester.py
    tty: true

